'use client';
import {useState} from 'react';
import {Area,AreaChart,ResponsiveContainer,XAxis,Tooltip} from 'recharts';
import {Bell,CarFront,ChevronDown,CircleDollarSign,FileText,Fuel,Gauge,History,Home,MoreHorizontal,Plus,Settings,ShieldCheck,Sparkles,Wrench} from 'lucide-react';
const points=[34,62,45,88,57,73,42].map((km,i)=>({day:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i],km}));
const nav=[[Home,'Dashboard'],[CarFront,'My vehicles'],[Gauge,'Trips'],[Fuel,'Fuel'],[Wrench,'Services'],[History,'History'],[CircleDollarSign,'Expenses'],[FileText,'Reports']] as const;
export default function HomePage(){const[active,setActive]=useState('Dashboard');const[menu,setMenu]=useState(false);const[note,setNote]=useState('');const open=(x:string)=>{setActive(x);setNote(`${x} opened`)};return <main className="app">
<aside><div className="logo"><b><Gauge/></b>motora</div><nav>{nav.map(([Icon,label])=><button key={label} className={active===label?'on':''} onClick={()=>open(label)}><Icon/>{label}</button>)}</nav><div className="aside-end"><button><Bell/>Notifications<i/></button><button><Settings/>Settings</button><section><strong>7 days free</strong><small>Then $9.99/month</small><button onClick={()=>setNote('Billing portal opened')}>Manage plan</button></section><div className="user"><b>TM</b><span><strong>Thabo M.</strong><small>Premium trial</small></span><MoreHorizontal/></div></div></aside>
<section className="main"><header><div><small>MONDAY, 7 SEPTEMBER</small><h1>Good morning, Thabo</h1></div><button className="selector"><span><CarFront/></span><b>2019 Toyota Hilux<small>ABC 123 GP</small></b><ChevronDown/></button></header>
<div className="content">{note&&<div className="notice"><Sparkles/>{note}</div>}<section className="hero"><div className="car"><CarFront/></div><div><em>â— HEALTHY</em><h2>2019 Toyota Hilux</h2><p>2.8 GD-6 Raider 4x4 â€¢ Diesel â€¢ Automatic</p><label>Current odometer <strong>126,450 <small>km</small></strong><button onClick={()=>setMenu(true)}><Plus/>Update</button></label></div><div className="score"><b>87<small>/100</small></b><span>Vehicle health<strong>Good</strong><small>Everything looks on track</small></span></div></section>
<section className="quick">{[[Fuel,'Fuel','blue'],[Gauge,'Trip','green'],[Wrench,'Service','orange'],[ShieldCheck,'Repair','purple']].map(([Icon,label,color]:any)=><button key={label} onClick={()=>setNote(`Add ${label.toLowerCase()} form opened`)}><i className={color}><Icon/></i><span><small>QUICK ADD</small><strong>{label}</strong></span><Plus/></button>)}</section>
<section className="panel distance"><div className="title"><span><i><Gauge/></i><b>Distance travelled<small>Your movement at a glance</small></b></span><button>This week <ChevronDown/></button></div><div className="stats">{[['Today','42','+12% vs avg.'],['This week','285','On track'],['This month','1,248','âˆ’4% vs Aug'],['This year','14,820','+8% vs 2025']].map(x=><div key={x[0]}><small>{x[0]}</small><strong>{x[1]} <em>km</em></strong><i>{x[2]}</i></div>)}</div><div className="chart"><ResponsiveContainer><AreaChart data={points}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#16b889" stopOpacity=".3"/><stop offset="1" stopColor="#16b889" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false}/><Tooltip/><Area dataKey="km" type="monotone" stroke="#16b889" strokeWidth={3} fill="url(#g)"/></AreaChart></ResponsiveContainer></div></section>
<section className="cards"><article className="panel"><div className="title"><span><i><Fuel/></i><b>Fuel economy<small>Last 30 days</small></b></span><MoreHorizontal/></div><div className="large">8.4 <small>L/100 km</small><em>â†“ 5.2% improved</em></div><div className="bars">{[44,65,52,76,60,82,68,90,73,85,78,94].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><footer><span>Monthly fuel cost</span><b>R 2,840.60</b></footer></article><article className="panel"><div className="title"><span><i className="orange"><Wrench/></i><b>Next service<small>Major service</small></b></span><MoreHorizontal/></div><div className="duo"><span>Due at<strong>130,000 km</strong></span><span>Remaining<strong>3,550 km</strong></span></div><div className="progress"><i/></div><p>ðŸ“… Estimated in 76 days</p><button className="outline" onClick={()=>setNote('Service scheduled')}>Schedule service</button></article><article className="panel"><div className="title"><span><i className="blue"><ShieldCheck/></i><b>Documents<small>Renewals & protection</small></b></span><MoreHorizontal/></div>{[['Vehicle licence','Expires 22 Oct 2026','45 days'],['Insurance','Renews 15 Dec 2026','99 days']].map(x=><div className="doc" key={x[0]}><i><FileText/></i><span><strong>{x[0]}</strong><small>{x[1]}</small></span><em>{x[2]}</em></div>)}<button className="outline" onClick={()=>open('Documents')}>View documents</button></article></section>
<section className="bottom"><article className="insight"><i><Sparkles/></i><div><small>SMART INSIGHT</small><h3>Youâ€™re driving more efficiently</h3><p>Your average fuel economy improved by 5.2% this month. Thatâ€™s an estimated saving of <b>R148.</b></p></div><button onClick={()=>setNote('Insight marked as read')}>Got it</button></article><article className="panel recent"><div className="title"><span><i><History/></i><b>Recent activity<small>Your latest vehicle records</small></b></span><button>View all</button></div>{[['Fuel fill-up','45.2 L â€¢ Shell Sandton','R1,020'],['Trip','Work â€¢ 42 km','126,450 km'],['Major service','Toyota Fourways','R4,850']].map((x,i)=><div className="row" key={x[0]}><i>{i===0?<Fuel/>:i===1?<Gauge/>:<Wrench/>}</i><span><b>{x[0]}</b><small>{x[1]}</small></span><b>{x[2]}</b></div>)}</article></section></div></section>
<button className="fab" onClick={()=>setMenu(!menu)}><Plus/></button>{menu&&<div className="menu"><b>Quick add</b>{['Fuel','Trip','Odometer','Service','Repair','Expense','Tyre record','Reminder'].map(x=><button key={x} onClick={()=>{setMenu(false);setNote(`Add ${x.toLowerCase()} form opened`)}}><Plus/>Add {x}</button>)}</div>}<nav className="mobile"><button><Home/>Home</button><button><CarFront/>Vehicle</button><button className="add" onClick={()=>setMenu(!menu)}><Plus/></button><button><Fuel/>Fuel</button><button><MoreHorizontal/>More</button></nav></main>}

