'use client';
import {useState} from 'react';
import {Area,AreaChart,ResponsiveContainer,XAxis,Tooltip} from 'recharts';
import {Bell,CarFront,ChevronDown,CircleDollarSign,FileText,Fuel,Gauge,History,Home,MoreHorizontal,Plus,Settings,ShieldCheck,Sparkles,Wrench} from 'lucide-react';
const points=[34,62,45,88,57,73,42].map((km,i)=>({day:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i],km}));
const nav=[[Home,'Dashboard'],[CarFront,'My vehicles'],[Gauge,'Trips'],[Fuel,'Fuel'],[Wrench,'Services'],[History,'History'],[CircleDollarSign,'Expenses'],[FileText,'Reports']] as const;
const viewData:Record<string,{title:string;subtitle:string;action:string;stats:string[][];rows:string[][]}>={
 'My vehicles':{title:'My vehicles',subtitle:'Manage every vehicle in one place',action:'Add vehicle',stats:[['Vehicles','2'],['Total distance','148,920 km'],['Combined value','R 685,000']],rows:[['2019 Toyota Hilux','ABC 123 GP','126,450 km'],['2022 Volkswagen Polo','CA 482-119','22,470 km']]},
 Trips:{title:'Trips & mileage',subtitle:'See exactly where your kilometres go',action:'Add trip',stats:[['This month','1,248 km'],['Daily average','41.6 km'],['Work travel','642 km']],rows:[['Work commute','Today, 08:12','42 km'],['Shopping','6 Sep 2026','18 km'],['Client visit','5 Sep 2026','76 km']]},
 Fuel:{title:'Fuel tracking',subtitle:'Monitor fill-ups, price and efficiency',action:'Add fuel',stats:[['Average economy','8.4 L/100 km'],['This month','R 2,840.60'],['Cost per km','R 1.92']],rows:[['Shell Sandton','6 Sep 2026 • 45.2 L','R 1,020.16'],['Engen Bryanston','25 Aug 2026 • 43.8 L','R 985.50'],['BP Fourways','14 Aug 2026 • 46.1 L','R 1,047.93']]},
 Services:{title:'Service history',subtitle:'Maintenance completed and coming up',action:'Add service',stats:[['Next service','3,550 km'],['Services logged','12'],['Service spend','R 8,940']],rows:[['Major service','18 Jul 2026 • 125,000 km','R 4,850'],['Oil change','12 Feb 2026 • 118,420 km','R 1,250'],['Brake service','4 Nov 2025 • 112,300 km','R 2,840']]},
 History:{title:'Vehicle history',subtitle:'Your complete vehicle timeline',action:'Add record',stats:[['Records','84'],['Latest update','Today'],['Documents','16']],rows:[['Trip • Work','Today • 126,450 km','42 km'],['Fuel • Shell Sandton','6 Sep 2026 • 126,408 km','R 1,020'],['Major service','18 Jul 2026 • 125,000 km','R 4,850']]},
 Expenses:{title:'Vehicle expenses',subtitle:'Understand every rand your vehicle costs',action:'Add expense',stats:[['This month','R 6,428'],['This year','R 54,390'],['Cost per km','R 3.67']],rows:[['Fuel','September 2026','R 2,840'],['Insurance','September 2026','R 1,250'],['Major service','July 2026','R 4,850']]},
 Reports:{title:'Reports',subtitle:'Export clear summaries for any period',action:'Generate report',stats:[['Available reports','7'],['Last export','31 Aug'],['Current period','2026']],rows:[['Annual vehicle report','Full cost and mileage summary','PDF • CSV'],['Fuel consumption report','Efficiency and price trends','PDF • CSV'],['Service history report','All maintenance records','PDF • CSV']]},
 Documents:{title:'Documents',subtitle:'Licence, insurance, invoices and receipts',action:'Upload document',stats:[['Documents','16'],['Expiring soon','1'],['Storage used','24.8 MB']],rows:[['Vehicle licence','Expires 22 Oct 2026','45 days'],['Insurance policy','Renews 15 Dec 2026','99 days'],['Major service invoice','Uploaded 18 Jul 2026','PDF']]}
};
function SectionView({name,onAction}:{name:string;onAction:(message:string)=>void}){const v=viewData[name]??viewData.History;return <section className="section-view"><div className="view-head"><div><small>2019 TOYOTA HILUX</small><h2>{v.title}</h2><p>{v.subtitle}</p></div><button onClick={()=>onAction(`${v.action} form opened`)}><Plus/>{v.action}</button></div><div className="view-stats">{v.stats.map(([label,value])=><article className="panel" key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><article className="panel view-list"><div className="list-head"><b>{name==='Reports'?'Available reports':'Recent records'}</b><button>Filter <ChevronDown/></button></div>{v.rows.map(([title,detail,value])=><button className="view-row" key={title} onClick={()=>onAction(`${title} selected`)}><i>{name==='Fuel'?<Fuel/>:name==='Services'?<Wrench/>:name==='Expenses'?<CircleDollarSign/>:name==='My vehicles'?<CarFront/>:<FileText/>}</i><span><strong>{title}</strong><small>{detail}</small></span><b>{value}</b><ChevronDown/></button>)}</article></section>}
export default function HomePage(){const[active,setActive]=useState('Dashboard');const[menu,setMenu]=useState(false);const[note,setNote]=useState('');const open=(x:string)=>{setActive(x);setNote(`${x} opened`)};return <main className="app">
<aside><div className="logo"><b><Gauge/></b>motora</div><nav>{nav.map(([Icon,label])=><button key={label} className={active===label?'on':''} onClick={()=>open(label)}><Icon/>{label}</button>)}</nav><div className="aside-end"><button><Bell/>Notifications<i/></button><button><Settings/>Settings</button><section><strong>7 days free</strong><small>Then $9.99/month</small><button onClick={()=>setNote('Billing portal opened')}>Manage plan</button></section><div className="user"><b>TM</b><span><strong>Thabo M.</strong><small>Premium trial</small></span><MoreHorizontal/></div></div></aside>
<section className="main"><header><div><small>MONDAY, 7 SEPTEMBER</small><h1>Good morning, Thabo</h1></div><button className="selector"><span><CarFront/></span><b>2019 Toyota Hilux<small>ABC 123 GP</small></b><ChevronDown/></button></header>
<div className="content">{note&&<div className="notice"><Sparkles/>{note}</div>}{active==='Dashboard'?<><section className="hero"><div className="car"><CarFront/></div><div><em>● HEALTHY</em><h2>2019 Toyota Hilux</h2><p>2.8 GD-6 Raider 4x4 • Diesel • Automatic</p><label>Current odometer <strong>126,450 <small>km</small></strong><button onClick={()=>setMenu(true)}><Plus/>Update</button></label></div><div className="score"><b>87<small>/100</small></b><span>Vehicle health<strong>Good</strong><small>Everything looks on track</small></span></div></section>
<section className="quick">{[[Fuel,'Fuel','blue'],[Gauge,'Trip','green'],[Wrench,'Service','orange'],[ShieldCheck,'Repair','purple']].map(([Icon,label,color]:any)=><button key={label} onClick={()=>setNote(`Add ${label.toLowerCase()} form opened`)}><i className={color}><Icon/></i><span><small>QUICK ADD</small><strong>{label}</strong></span><Plus/></button>)}</section>
<section className="panel distance"><div className="title"><span><i><Gauge/></i><b>Distance travelled<small>Your movement at a glance</small></b></span><button>This week <ChevronDown/></button></div><div className="stats">{[['Today','42','+12% vs avg.'],['This week','285','On track'],['This month','1,248','−4% vs Aug'],['This year','14,820','+8% vs 2025']].map(x=><div key={x[0]}><small>{x[0]}</small><strong>{x[1]} <em>km</em></strong><i>{x[2]}</i></div>)}</div><div className="chart"><ResponsiveContainer><AreaChart data={points}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#16b889" stopOpacity=".3"/><stop offset="1" stopColor="#16b889" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false}/><Tooltip/><Area dataKey="km" type="monotone" stroke="#16b889" strokeWidth={3} fill="url(#g)"/></AreaChart></ResponsiveContainer></div></section>
<section className="cards"><article className="panel"><div className="title"><span><i><Fuel/></i><b>Fuel economy<small>Last 30 days</small></b></span><MoreHorizontal/></div><div className="large">8.4 <small>L/100 km</small><em>↓ 5.2% improved</em></div><div className="bars">{[44,65,52,76,60,82,68,90,73,85,78,94].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><footer><span>Monthly fuel cost</span><b>R 2,840.60</b></footer></article><article className="panel"><div className="title"><span><i className="orange"><Wrench/></i><b>Next service<small>Major service</small></b></span><MoreHorizontal/></div><div className="duo"><span>Due at<strong>130,000 km</strong></span><span>Remaining<strong>3,550 km</strong></span></div><div className="progress"><i/></div><p>📅 Estimated in 76 days</p><button className="outline" onClick={()=>setNote('Service scheduled')}>Schedule service</button></article><article className="panel"><div className="title"><span><i className="blue"><ShieldCheck/></i><b>Documents<small>Renewals & protection</small></b></span><MoreHorizontal/></div>{[['Vehicle licence','Expires 22 Oct 2026','45 days'],['Insurance','Renews 15 Dec 2026','99 days']].map(x=><div className="doc" key={x[0]}><i><FileText/></i><span><strong>{x[0]}</strong><small>{x[1]}</small></span><em>{x[2]}</em></div>)}<button className="outline" onClick={()=>open('Documents')}>View documents</button></article></section>
<section className="bottom"><article className="insight"><i><Sparkles/></i><div><small>SMART INSIGHT</small><h3>You’re driving more efficiently</h3><p>Your average fuel economy improved by 5.2% this month. That’s an estimated saving of <b>R148.</b></p></div><button onClick={()=>setNote('Insight marked as read')}>Got it</button></article><article className="panel recent"><div className="title"><span><i><History/></i><b>Recent activity<small>Your latest vehicle records</small></b></span><button onClick={()=>open('History')}>View all</button></div>{[['Fuel fill-up','45.2 L • Shell Sandton','R1,020'],['Trip','Work • 42 km','126,450 km'],['Major service','Toyota Fourways','R4,850']].map((x,i)=><div className="row" key={x[0]}><i>{i===0?<Fuel/>:i===1?<Gauge/>:<Wrench/>}</i><span><b>{x[0]}</b><small>{x[1]}</small></span><b>{x[2]}</b></div>)}</article></section></>:<SectionView name={active} onAction={setNote}/>}</div></section>
<button className="fab" onClick={()=>setMenu(!menu)}><Plus/></button>{menu&&<div className="menu"><b>Quick add</b>{['Fuel','Trip','Odometer','Service','Repair','Expense','Tyre record','Reminder'].map(x=><button key={x} onClick={()=>{setMenu(false);setNote(`Add ${x.toLowerCase()} form opened`)}}><Plus/>Add {x}</button>)}</div>}<nav className="mobile"><button className={active==='Dashboard'?'on':''} onClick={()=>open('Dashboard')}><Home/>Home</button><button className={active==='My vehicles'?'on':''} onClick={()=>open('My vehicles')}><CarFront/>Vehicle</button><button className="add" onClick={()=>setMenu(!menu)}><Plus/></button><button className={active==='Fuel'?'on':''} onClick={()=>open('Fuel')}><Fuel/>Fuel</button><button className={active==='History'?'on':''} onClick={()=>open('History')}><MoreHorizontal/>More</button></nav></main>}

